ALTER TABLE users
  ADD COLUMN IF NOT EXISTS no_nik VARCHAR(30) NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS no_kk VARCHAR(30) NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS nomor_akta_lahir VARCHAR(50) NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS agama VARCHAR(30) NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS tempat_tinggal VARCHAR(255) NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS mode_transportasi VARCHAR(255) NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS anak_ke INT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS jumlah_bersaudara INT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS riwayat_penyakit TEXT NOT NULL DEFAULT '';
