ALTER TABLE users ADD COLUMN IF NOT EXISTS npsn VARCHAR(50);
ALTER TABLE users ADD COLUMN IF NOT EXISTS jenjang_sekolah VARCHAR(50);
ALTER TABLE test_batches ADD COLUMN IF NOT EXISTS jenjang_sekolah VARCHAR(50);
