package models

import (
	"time"

	"github.com/beego/beego/v2/client/orm"
	"golang.org/x/crypto/bcrypt"
)

type Gender string

type Role string

const (
	GenderLakiLaki  Gender = "laki_laki"
	GenderPerempuan Gender = "perempuan"

	RoleSiswa     Role = "siswa"
	RoleGuru      Role = "guru"
	RolePekerja   Role = "pekerja"
	RoleMahasiswa Role = "mahasiswa"
	RoleUmum      Role = "umum"
	RoleAdmin     Role = "admin"
	RoleSekolah   Role = "sekolah"
)

// SekolahList adalah daftar sekolah yang tersedia di sistem (dummy untuk
// keperluan onboarding & filter data sekolah).
var SekolahList = []string{
	"<truncated 118326 bytes>",
	"SMA 1 Barunawati",
	"SMA 1 Cawang Baru",
	"SMA 1 Yadika",
	"SMA 17 Agustus 45 Jakarta",
	"SMA 2 Perguruan Cikini",
	"SMA 28 Oktober 1928",
	"SMA 3 Kalam Kudus",
	"SMA Adi Luhur Jakarta",
	"SMA Advent 1 Jakarta",
	"SMA Advent Salemba",
	"SMA Al Azhar Syifa Budi",
	"SMA Al Chasanah",
	"SMA Al Falah",
	"SMA Al Ghurabaa Jakarta",
	"SMA Al Hikmah Jakarta",
	"SMA Al Huda Cengkareng",
	"SMA Al Jihad Jakarta",
	"SMA Al Kamal",
	"SMA Al Kautsar",
	"SMA Al Khairiyah Jakarta",
	"SMA Al Muhajirin Jakarta",
	"SMA Al Wildan 4 Islamic School Jakarta",
	"SMA Al Wildan Islamic School 10 Jakarta",
	"SMA Angkasa 1 H Perdanakusuma",
	"SMA Angkasa 2 H Perdanakusuma",
	"SMA Asisi Jakarta",
	"SMA Avicenna Jagakarsa",
	"SMA BPS&K I",
	"SMA Bakti Idhata Jakarta",
	"SMA Bakti Mulya 400",
	"SMA Baptis Cengkareng Indah",
	"SMA Bhakti Utama",
	"SMA Bhineka Tunggal Ika",
	"SMA Bina Dharma Jakarta",
	"SMA Bina Kusuma Mulia",
	"SMA Bina Maju Bangsa",
	"SMA Bina Pangudi Luhur Jakarta",
	"SMA Blossom School",
	"SMA Buana Siswa",
	"SMA Budaya",
	"SMA Budaya Jakarta",
	"SMA Budhaya 2 St Agustinus",
	"SMA Budhi Warman 1",
	"SMA Budhi Warman 2",
	"SMA Budi Agung",
	"SMA Budi Mulia",
	"SMA Budi Mulia Utama Jakarta",
	"SMA Budi Murni 2",
	"SMA Bukit Mulia",
	"SMA Bunda Hati Kudus",
	"SMA Bunda Kandung Jakarta",
	"SMA Bunda Mulia",
	"SMA Bunda Mulia Jakarta",
	"SMA Bunga Hati Bangsa",
	"SMA Cahaya Fadilah",
	"SMA Cahaya Kudus Jakarta",
	"SMA Cahaya Sakti Jakarta",
	"SMA Cakra Buana",
	"SMA Candra Naya",
	"SMA Cenderawasih 1",
	"SMA Cengkareng 1",
	"SMA Chandra Kusuma Jakarta",
	"SMA Charitas",
	"SMA Chartar Buana",
	"SMA Cikal",
	"SMA Cikal Amri",
	"SMA Cinta Kasih Tzu Chi",
	"SMA Cinta Mulia Chong Mian",
	"SMA Citra Kasih",
	"SMA Citra Kasih Don Bosco Pondok Indah",
	"SMA Corpatarin Jakarta",
	"SMA Damai",
	"SMA Darma Satria Persada",
	"SMA Darul Maarif Jakarta",
	"SMA Darunnajah",
	"SMA Dewi Sartika",
	"SMA Dewi Sartika YBW Jakarta",
	"SMA Dhammasavana",
	"SMA Dharma Budhi Bhakti Jakarta",
	"SMA Dharma Jaya",
	"SMA Dharma Karya Jakarta",
	"SMA Dharma Putra Jakarta",
	"SMA Dharma Suci Jakarta",
	"SMA Dian Harapan",
	"SMA Dian Kasih",
	"SMA Dian Persada Jakarta",
	"SMA Diponegoro 1 Jakarta",
	"SMA Diponegoro 2 Jakarta",
	"SMA Don Bosco 1 Jakarta",
	"SMA Don Bosco II",
	"SMA Dwi Saka Jakarta",
	"SMA EMIISc Jakarta",
	"SMA Embun Pagi Islamic School",
	"SMA Eunoia Intercultural School",
	"SMA Fajrul Islam",
	"SMA Fatahillah",
	"SMA Fatahillah Jakarta",
	"SMA Fons Vitae 1 Jakarta",
	"SMA Fons Vitae 2 Jakarta",
	"SMA Fransiskus 1 Jakarta",
	"SMA Fransiskus 2 Jakarta",
	"SMA Galatia 3",
	"SMA Garuda Cendekia",
	"SMA Gideon Jakarta",
	"SMA Gita Kirti 2",
	"SMA Gita Kirtti 3 Jakarta",
	"SMA Global Islamic School",
	"SMA Global Mandiri",
	"SMA Global Nusantara School",
	"SMA Gonzaga Jakarta",
	"SMA Hang Tuah 1 Jakarta",
	"SMA Harapan Jaya",
	"SMA Harapan Kasih Jakarta",
	"SMA Hati Suci",
	"SMA Highfield",
	"SMA IGN Slamet Riyadi",
	"SMA IP Yakin",
	"SMA IT Al Halimiyah Jakarta",
	"SMA IT Buahati Islamic School",
	"SMA Ichthus Jakarta Barat",
	"SMA Impian Bunda",
	"SMA International Islamic High School (IIHS)?action=edit&redlink=1)",
	"SMA Islam Al Azhar 1 Jakarta",
	"SMA Islam Al Azhar 19",
	"SMA Islam Al Azhar 2 Jakarta",
	"SMA Islam Al Azhar 20 Kembangan",
	"SMA Islam Al Azhar 3 Jakarta",
	"SMA Islam Al Azhar Kelapa Gading",
	"SMA Islam Al Izhar Pondok Labu",
	"SMA Islam Al Jihad Jakarta",
	"SMA Islam Al Kholidin Jakarta",
	"SMA Islam Al Maruf",
	"SMA Islam Annajah",
	"SMA Islam As Syafiiyah 01",
	"SMA Islam Harapan Ibu",
	"SMA Islam PB Soedirman",
	"SMA Islam Said Na'um Jakarta",
	"SMA Islam Tambora",
	"SMA Islam Terpadu Almaka",
	"SMA Jac",
	"SMA Jagakarsa",
	"SMA Jakarta Islamic School",
	"SMA Jakarta Montessori",
	"SMA Josua",
	"SMA Jubilee",
	"SMA Kairos Gracia",
	"SMA Kanaan Global School",
	"SMA Kanisius Jakarta",
	"SMA Kapin",
	"SMA Kartika VIII-1 Jakarta",
	"SMA Kartika X-1",
	"SMA Kartini 1 Jakarta",
	"SMA Kasih Bagi Bangsa",
	"SMA Kasih Immanuel",
	"SMA Kasih Karunia",
	"SMA Katholik Bintang Kejora",
	"SMA Katolik Abdi Siswa",
	"SMA Katolik Diakonia Jakarta",
	"SMA Katolik Lia Stephanie",
	"SMA Katolik Nusa Melati",
	"SMA Katolik Ricci",
	"SMA Katolik Sang Timur",
	"SMA Keluarga Widuri Jakarta",
	"SMA Kemala Bhayangkari 1",
	"SMA Kemurnian II",
	"SMA Kharismawita Jakarta",
	"SMA Kristen 1 BPK Penabur",
	"SMA Kristen 2 BPK Penabur",
	"SMA Kristen 3 Penabur",
	"SMA Kristen 4 Penabur",
	"SMA Kristen 5 Penabur",
	"SMA Kristen 6 Penabur",
	"SMA Kristen 7 Penabur",
	"SMA Kristen Almasih",
	"SMA Kristen Berkat Jakarta",
	"SMA Kristen Bethel",
	"SMA Kristen Calvin",
	"SMA Kristen Immanuel",
	"SMA Kristen Ipeka Pluit",
	"SMA Kristen Ipeka Puri Indah",
	"SMA Kristen Ipeka Sunter",
	"SMA Kristen Ipeka Tomang",
	"SMA Kristen Kalam Kudus II",
	"SMA Kristen Kanaan Jakarta",
	"SMA Kristen Karunia Jakarta",
	"SMA Kristen Kasih Kemuliaan",
	"SMA Kristen Ketapang 1 Jakarta",
	"SMA Kristen Pancaran Berkat",
	"SMA Kristen Saint John",
	"SMA Kristen Samaria Kudus",
	"SMA Kristen Tiara Kasih",
	"SMA Kristen Tunas Bangsa",
	"SMA Kristen Yusuf",
	"SMA Labschool Bintaro",
	"SMA Labschool Ciracas",
	"SMA Labschool Jakarta",
	"SMA Labschool Kebayoran",
	"SMA Lamaholot",
	"SMA Laphat Plus",
	"SMA Lilin Bangsa Intercultural School",
	"SMA Mahabodhi Vidya",
	"SMA Mahatma Gading",
	"SMA Maitreyawira Jakarta",
	"SMA Makarios",
	"SMA Malahayati",
	"SMA Mandala Cendekia",
	"SMA Marie Joseph",
	"SMA Mentari Grand Surya",
	"SMA Methodist Jakarta",
	"SMA Minhaajurrosyidiin",
	"SMA Muhammadiyah 1 Jakarta",
	"SMA Muhammadiyah 11 Jakarta",
	"SMA Muhammadiyah 12 Jakarta",
	"SMA Muhammadiyah 13 Jakarta",
	"SMA Muhammadiyah 14 Jakarta",
	"SMA Muhammadiyah 15",
	"SMA Muhammadiyah 16 Jakarta",
	"SMA Muhammadiyah 18 Jakarta",
	"SMA Muhammadiyah 2 Jakarta",
	"SMA Muhammadiyah 23 Jakarta",
	"SMA Muhammadiyah 24",
	"SMA Muhammadiyah 3 Jakarta",
	"SMA Muhammadiyah 4 Jakarta",
	"SMA Muhammadiyah 5 Jakarta",
	"SMA Mutiara 1 Jakarta",
	"SMA Mutiara Bangsa 3",
	"SMA Muttaqien Jakarta",
	"SMA Nabawi Islamic School",
	"SMA Nahdlatul Wathan",
	"SMA Nasional Nusantara",
	"SMA Negeri 1",
	"SMA Negeri 10",
	"SMA Negeri 100",
	"SMA Negeri 101",
	"SMA Negeri 102",
	"SMA Negeri 103",
	"SMA Negeri 104",
	"SMA Negeri 105",
	"SMA Negeri 106",
	"SMA Negeri 107",
	"SMA Negeri 108",
	"SMA Negeri 109",
	"SMA Negeri 11",
	"SMA Negeri 110",
	"SMA Negeri 111",
	"SMA Negeri 112",
	"SMA Negeri 113",
	"SMA Negeri 114",
	"SMA Negeri 115",
	"SMA Negeri 116",
	"SMA Negeri 117",
	"SMA Negeri 12",
	"SMA Negeri 13",
	"SMA Negeri 14",
	"SMA Negeri 15",
	"SMA Negeri 16",
	"SMA Negeri 17",
	"SMA Negeri 18",
	"SMA Negeri 19",
	"SMA Negeri 2",
	"SMA Negeri 20",
	"SMA Negeri 21",
	"SMA Negeri 22",
	"SMA Negeri 23",
	"SMA Negeri 24",
	"SMA Negeri 25",
	"SMA Negeri 26",
	"SMA Negeri 27",
	"SMA Negeri 28",
	"SMA Negeri 29",
	"SMA Negeri 3",
	"SMA Negeri 30",
	"SMA Negeri 31",
	"SMA Negeri 32",
	"SMA Negeri 33",
	"SMA Negeri 34",
	"SMA Negeri 35",
	"SMA Negeri 36",
	"SMA Negeri 37",
	"SMA Negeri 38",
	"SMA Negeri 39",
	"SMA Negeri 4",
	"SMA Negeri 40",
	"SMA Negeri 41",
	"SMA Negeri 42",
	"SMA Negeri 43",
	"SMA Negeri 44",
	"SMA Negeri 45",
	"SMA Negeri 46",
	"SMA Negeri 47",
	"SMA Negeri 48",
	"SMA Negeri 49",
	"SMA Negeri 5",
	"SMA Negeri 50",
	"SMA Negeri 51",
	"SMA Negeri 52",
	"SMA Negeri 53",
	"SMA Negeri 54",
	"SMA Negeri 55",
	"SMA Negeri 56",
	"SMA Negeri 57",
	"SMA Negeri 58",
	"SMA Negeri 59",
	"SMA Negeri 6",
	"SMA Negeri 60",
	"SMA Negeri 61",
	"SMA Negeri 62",
	"SMA Negeri 63",
	"SMA Negeri 64",
	"SMA Negeri 65",
	"SMA Negeri 66",
	"SMA Negeri 67",
	"SMA Negeri 68",
	"SMA Negeri 69",
	"SMA Negeri 7",
	"SMA Negeri 70",
	"SMA Negeri 71",
	"SMA Negeri 72",
	"SMA Negeri 73",
	"SMA Negeri 74",
	"SMA Negeri 75",
	"SMA Negeri 76",
	"SMA Negeri 77",
	"SMA Negeri 78",
	"SMA Negeri 79",
	"SMA Negeri 8",
	"SMA Negeri 80",
	"SMA Negeri 81",
	"SMA Negeri 82",
	"SMA Negeri 83",
	"SMA Negeri 84",
	"SMA Negeri 85",
	"SMA Negeri 86",
	"SMA Negeri 87",
	"SMA Negeri 88",
	"SMA Negeri 89",
	"SMA Negeri 9",
	"SMA Negeri 90",
	"SMA Negeri 91",
	"SMA Negeri 92",
	"SMA Negeri 93",
	"SMA Negeri 94",
	"SMA Negeri 95",
	"SMA Negeri 96",
	"SMA Negeri 97",
	"SMA Negeri 98",
	"SMA Negeri 99",
	"SMA Negeri Ragunan",
	"SMA Negeri Unggulan M. H. Thamrin",
	"SMA Nizamia Andalusia",
	"SMA Notre Dame",
	"SMA Nurul Falah Jakarta",
	"SMA Nurul Huda Jakarta",
	"SMA Nusantara Jakarta",
	"SMA Nusantara Permai",
	"SMA PGRI 1 Jakarta",
	"SMA PGRI 12 Jakarta",
	"SMA PGRI 24 Jakarta",
	"SMA PGRI 3 Jakarta",
	"SMA PGRI 4 Jakarta",
	"SMA PKP",
	"SMA PSKD 1 Jakarta",
	"SMA PSKD 3 Jakarta",
	"SMA PSKD 4 Jakarta",
	"SMA PSKD II Jakarta",
	"SMA Padindi",
	"SMA Pah Tsung",
	"SMA Pangudi Luhur Jakarta",
	"SMA Pangudi Rahayu",
	"SMA Paskalis",
	"SMA Pattimura Jakarta",
	"SMA Pelangi Kasih",
	"SMA Pelita 2",
	"SMA Pelita Anugerah",
	"SMA Pelita IV",
	"SMA Pelita Kasih",
	"SMA Pelita Tiga No 3 Jakarta",
	"SMA Pembangunan III YPI",
	"SMA Perguruan Advent XV",
	"SMA Perguruan Cikini Jakarta",
	"SMA Perguruan Ksatrya",
	"SMA Perguruan Nasional Jakarta",
	"SMA Perguruan Rakyat 1 Jakarta",
	"SMA Perguruan Rakyat 2 Jakarta",
	"SMA Perguruan Rakyat 3 Jakarta",
	"SMA Perkumpulan Mandiri",
	"SMA Permai Jakarta",
	"SMA Permata Indah Jakarta",
	"SMA Petra",
	"SMA Plus Khadijah Islamic School",
	"SMA Pratama",
	"SMA Prestasi Prima",
	"SMA Providentia",
	"SMA Purnama Jakarta",
	"SMA Pusaka 1 Jakarta",
	"SMA Pusaka Abadi Jakarta",
	"SMA Putra 1",
	"SMA Regina Pacis",
	"SMA ST Alexius Jakarta",
	"SMA ST Antonius Jakarta",
	"SMA Saint Johns School",
	"SMA Saint Peter",
	"SMA San Marino",
	"SMA Santa Theresia",
	"SMA Santa Ursula",
	"SMA Santika",
	"SMA Santo Bellarminus",
	"SMA Santo Kristoforus 1",
	"SMA Santo Kristoforus 2",
	"SMA Santo Leo",
	"SMA Santo Leo II",
	"SMA Santo Lukas 1 Jakarta",
	"SMA Santo Paulus Jakarta",
	"SMA Santo Yakobus Jakarta",
	"SMA Santo Yoseph Jakarta",
	"SMA Sapta Kharisma Jakarta",
	"SMA Sentosa",
	"SMA Sinar Dharma",
	"SMA St Maria Della Strada",
	"SMA Stella Maris Jakarta",
	"SMA Sukses Abadi",
	"SMA Suluh Jakarta",
	"SMA Sumbangsih Jakarta",
	"SMA Sumpah Pemuda",
	"SMA Sunda Kelapa Jakarta",
	"SMA Taman Madya 5 Jakarta",
	"SMA Taman Madya I Jakarta",
	"SMA Tanjung Priok Jakarta",
	"SMA Tarakanita 1 Jakarta",
	"SMA Tarakanita 2",
	"SMA Tarsisius 1 Jakarta",
	"SMA Tarsisius II",
	"SMA Taruna Persada",
	"SMA Teladan 1 Jakarta",
	"SMA Tirtamarta BPK Penabur",
	"SMA Trampil 2 Jakarta",
	"SMA Tri Ratna",
	"SMA Triguna Jakarta",
	"SMA Trisoko Jakarta",
	"SMA Triwibawa Jakarta",
	"SMA Tunas Gading",
	"SMA Tunas Harapan",
	"SMA Tunas Indonesia",
	"SMA Tunas Karya Jakarta",
	"SMA Tunas Markatin Jakarta",
	"SMA Uswatun Hasanah Jakarta",
	"SMA Vianney",
	"SMA Villa Mas Jakarta",
	"SMA Wardaya",
	"SMA Westin",
	"SMA Widya Manggala Jakarta",
	"SMA Wijaya Jakarta",
	"SMA Wijaya Kusuma",
	"SMA Wijaya Kusuma Jakarta",
	"SMA YMIK 2 Jakarta",
	"SMA YP BDN",
	"SMA YP IPPI Jakarta",
	"SMA Yadika 2",
	"SMA Yadika 5",
	"SMA Yake Jakarta",
	"SMA Yaniic Jakarta",
	"SMA Yapermas Jakarta",
	"SMA Yappenda",
	"SMA Yaspi Jakarta",
	"SMA Yasporbi 1 Jakarta",
	"SMA Yusha Jakarta",
	"SMK 1 Barunawati",
	"SMK 1 Citra Adhi Pratama",
	"SMK 10 Nopember",
	"SMK 11 Maret",
	"SMK 17 Agustus 1945 2 Jakarta",
	"SMK 28 Oktober 1928 1",
	"SMK 28 Oktober 1928 2",
	"SMK 3 Perguruan Cikini",
	"SMK Ad Dawah",
	"SMK Adi Luhur Jakarta",
	"SMK Al Akhyar 1 Jakarta",
	"SMK Al Akhyar 2 Jakarta",
	"SMK Al Chasanah Jakarta",
	"SMK Al Fajar Jakarta",
	"SMK Al Falah",
	"SMK Al Fathiyah Jakarta",
	"SMK Al Firdaus",
	"SMK Al Hadiriyah",
	"SMK Al Hamidiyah",
	"SMK Al Hidayah 1 Jakarta",
	"SMK Al Hidayah 2 Jakarta",
	"SMK Al Hidayah Lestari",
	"SMK Al Huda Kebon Jeruk",
	"SMK Al Ihsan",
	"SMK Al Ihsan Jakarta",
	"SMK Al Irsyad",
	"SMK Al Irsyad Jakarta",
	"SMK Al Jihad Jakarta",
	"SMK Al Kautsar",
	"SMK Al Khairiyah 1 Jakarta",
	"SMK Al Khairiyah 2 Jakarta",
	"SMK Al Khairiyah Bahari",
	"SMK Al Ma'mur",
	"SMK Al Mafatih Jakarta",
	"SMK Al Makmur Jakarta",
	"SMK Al Miftahiyyah",
	"SMK Al Muttaqin",
	"SMK Al Wahyu Jakarta",
	"SMK Al Washilah 1 Jakarta",
	"SMK Al Washliyah Jakarta",
	"SMK Al Wathoniyah Jakarta",
	"SMK Amaliyah",
	"SMK An Nuriyah",
	"SMK Analis Kesehatan Ditkesad",
	"SMK Analis Kesehatan Tunas Medika",
	"SMK Angkasa 1 Jakarta",
	"SMK Ankes Tunas Harapan",
	"SMK Ar Raisiyah Husada",
	"SMK Ar Raudhah Jakarta",
	"SMK As Sa`adah",
	"SMK As Saadah",
	"SMK As Syafi`iyah Jakarta",
	"SMK As Syafiiyah 2",
	"SMK Asisi",
	"SMK At Taqwa",
	"SMK Atlantica Wisata Jakarta",
	"SMK Averus",
	"SMK Az Zahrah",
	"SMK BPS&K 1 Jakarta",
	"SMK BPS&K 2 Jakarta",
	"SMK Bakti 17",
	"SMK Bakti Idhata",
	"SMK Barunawati",
	"SMK Benteng Gading Jakarta",
	"SMK Bhakti",
	"SMK Bhakti 1 Jakarta",
	"SMK Bhakti Pertiwi Jakarta",
	"SMK Bhara Trikora 1 Jakarta",
	"SMK Bhumi Husada",
	"SMK Bina Bangsa",
	"SMK Bina Citra Asia",
	"SMK Bina Dharma",
	"SMK Bina Husada Mandiri",
	"SMK Bina Insan Mandiri",
	"SMK Bina Insan Nusantara",
	"SMK Bina Karya Jakarta",
	"SMK Bina Karya Utama Jakarta",
	"SMK Bina Manajemen Jakarta",
	"SMK Bina Medika Jakarta",
	"SMK Bina Nusa Mandiri",
	"SMK Bina Pangudi Luhur Jakarta",
	"SMK Bina Pembangunan 1",
	"SMK Bina Prestasi",
	"SMK Bina Putra Jakarta",
	"SMK Bintang Nusantara",
	"SMK Bisnis Indonesia Jakarta",
	"SMK Budaya Jakarta",
	"SMK Budhi Warman 1 Jakarta",
	"SMK Budhi Warman 2 Jakarta",
	"SMK Budi Agung",
	"SMK Budi Asih",
	"SMK Budi Mulia Utama",
	"SMK Budi Murni 1 Jakarta",
	"SMK Budi Murni 2",
	"SMK Budi Murni 3 Jakarta",
	"SMK Budi Murni 4 Jakarta",
	"SMK Budi Murni 5 Jakarta",
	"SMK Bunda Kandung Jakarta",
	"SMK Bunda Mulia",
	"SMK Bunda Mulia 1",
	"SMK Cahaya Prima",
	"SMK Cahaya Sakti Jakarta",
	"SMK Candra Naya",
	"SMK Caraka Nusantara",
	"SMK Cempaka",
	"SMK Cengkareng 1",
	"SMK Cengkareng 2",
	"SMK Cengkareng Jakarta",
	"SMK Cilincing 1 Jakarta",
	"SMK Cilincing 3 Jakarta",
	"SMK Cindera Mata Indah Jakarta",
	"SMK Cinta Kasih Tzu Chi",
	"SMK Cipta Karya Jakarta",
	"SMK Citra Bangsa",
	"SMK Citra Dharma Jakarta",
	"SMK Citra Mandiri Jakarta",
	"SMK Citra Utama",
	"SMK Corpatarin 1 Jakarta",
	"SMK Corpatarin 2 Jakarta",
	"SMK Cyber Media",
	"SMK Daarul Uluum",
	"SMK Daarussalaam Jakarta",
	"SMK Darul Maarif",
	"SMK Dental Asisten Sekesal Jakarta",
	"SMK Dewi Sartika",
	"SMK Dhamma Savana Jakarta",
	"SMK Dharma Karya",
	"SMK Dharma Paramitha",
	"SMK Dharma Putra 1",
	"SMK Dharma Surya",
	"SMK Dian Jakarta",
	"SMK Didaktika",
	"SMK Dinamika Pembangunan 1 Jakarta",
	"SMK Dinamika Pembangunan 2 Jakarta",
	"SMK Diponegoro 1 Jakarta",
	"SMK Duta Bangsa Jakarta",
	"SMK Duta Mas Jakarta",
	"SMK Eka Sakti",
	"SMK Era Pembangunan 3",
	"SMK Era Pembangunan Umat Jakarta",
	"SMK Fajar Indah",
	"SMK Farmasi BPK Penabur",
	"SMK Farmasi Ditkesad",
	"SMK Farmasi Ikifa",
	"SMK Farmasi Tunas Bangsa",
	"SMK Fatahillah",
	"SMK Fensensius Jakarta",
	"SMK Franciskus 2",
	"SMK Fransiskus 1 Jakarta",
	"SMK Gapura Merah Putih",
	"SMK Garuda Jakarta",
	"SMK Genesaret",
	"SMK Gita Kirtti 1 Jakarta",
	"SMK Gita Kirtti 2 Jakarta",
	"SMK Gita Wisata",
	"SMK Global 21 Jakarta",
	"SMK Global Cendekia",
	"SMK Global Multimedia",
	"SMK Global Persada",
	"SMK Grafika Desa Putera Jakarta",
	"SMK Grafika Yayasan Lektur",
	"SMK Gunung Jati Jakarta",
	"SMK Gutama Jakarta",
	"SMK Hang Tuah 1 Jakarta",
	"SMK Hang Tuah 2",
	"SMK Harapan 1 Jakarta",
	"SMK Harapan Jaya",
	"SMK Harapan Raya",
	"SMK Harnasto Institut Jakarta",
	"SMK Harvard Jakarta",
	"SMK Hatawana",
	"SMK Hidatha Jakarta",
	"SMK IMTAQ Darurrahim Jakarta",
	"SMK IP Yakin",
	"SMK IPTEK Jakarta",
	"SMK IT Aisyiyah",
	"SMK IT Assalaamah",
	"SMK Ibu Pertiwi 1 Jakarta",
	"SMK Ibu Pertiwi 2 Jakarta",
	"SMK Insan Aqilah 4",
	"SMK Insan Cendikia",
	"SMK Insan Cita",
	"SMK Insan Global",
	"SMK Insan Mulia Informatika",
	"SMK Insan Teknologi Jakarta",
	"SMK Islam Al Hikmah",
	"SMK Islam Al Makiyah",
	"SMK Islam Andalus",
	"SMK Islam Assaadatul Abadiyah Jakarta",
	"SMK Islam Bahagia",
	"SMK Islam Fatahillah Jakarta",
	"SMK Islam Malahayati",
	"SMK Islam PB Soedirman 1 Jakarta",
	"SMK Islam PB Soedirman 2 Jakarta",
	"SMK Islam Perti Jakarta",
	"SMK Islam Wijaya Kusuma",
	"SMK Islam YPS",
	"SMK Jagakarsa",
	"SMK Jakarta 1",
	"SMK Jakarta Barat 1",
	"SMK Jakarta Dua",
	"SMK Jakarta III",
	"SMK Jakarta IV",
	"SMK Jakarta Manajemen",
	"SMK Jakarta Pusat 1",
	"SMK Jakarta Raya 1",
	"SMK Jakarta Raya 2",
	"SMK Jakarta Timur 1",
	"SMK Jakarta Timur 2",
	"SMK Jakarta Wisata 1",
	"SMK Jaya Jakarta",
	"SMK Jayawisata 1",
	"SMK Jayawisata 2 Jakarta",
	"SMK Josua Jakarta",
	"SMK Kahuripan 1 Jakarta",
	"SMK Kalpataru Cakung Jakarta",
	"SMK Kampung Jawa Jakarta",
	"SMK Kartika X 1",
	"SMK Kartika X 2",
	"SMK Kartini",
	"SMK Karya Dharma 2 Jakarta",
	"SMK Karya Ekopin",
	"SMK Karya Guna Jakarta",
	"SMK Karya Teladan",
	"SMK Karya Wijaya Kusuma Jakarta",
	"SMK Kasih Ananda",
	"SMK Kasih Anugerah",
	"SMK Katolik Saint Joseph",
	"SMK Kawula Indonesia",
	"SMK Kawula Jakarta",
	"SMK Kebon Jeruk Jakarta",
	"SMK Kebudayaan",
	"SMK Keluarga Widuri",
	"SMK Kemala Bhayangkari 1 Jakarta",
	"SMK Kemala Bhayangkari Delog",
	"SMK Kencana 1 Jakarta",
	"SMK Kesatuan",
	"SMK Kesdam Jaya",
	"SMK Kesehatan Global Cendekia",
	"SMK Kesehatan Mulia Karya Husada",
	"SMK Kesehatan Sekawan",
	"SMK Kharismawita 1 Jakarta",
	"SMK Kharismawita 2 Jakarta",
	"SMK Krisanti",
	"SMK Kristen Bethel",
	"SMK Kristen Cendrawasih",
	"SMK Kristen Harapan Mulia",
	"SMK Kristen Kanaan",
	"SMK Kristen Pancaran Berkat",
	"SMK Kristen Rahmani",
	"SMK Ksatrya",
	"SMK LP3 Istana",
	"SMK L`pina Jakarta",
	"SMK Laboratorium Jakarta",
	"SMK Lagoa",
	"SMK Lamaholot Jakarta",
	"SMK Maarif Jakarta",
	"SMK Mahadhika 1 Jakarta",
	"SMK Mahadhika 2 Jakarta",
	"SMK Mahadhika 3 Jakarta",
	"SMK Mahadhika 4 Jakarta",
	"SMK Makarya 1 Jakarta",
	"SMK Makarya 2 Jakarta",
	"SMK Malaka Jakarta",
	"SMK Mandala Tiara Bangsa",
	"SMK Mardhika",
	"SMK Mardi Bakti Jakarta",
	"SMK Media Informatika",
	"SMK Media Karya",
	"SMK Medical High School",
	"SMK Mercusuar",
	"SMK Miftahul Falah Jakarta",
	"SMK Mitra Kencana Jakarta",
	"SMK Mitra Pembangunan",
	"SMK Muara Indonesia Jakarta",
	"SMK Muhammadiyah 1 Jakarta",
	"SMK Muhammadiyah 10 Jakarta",
	"SMK Muhammadiyah 11 Jakarta",
	"SMK Muhammadiyah 12",
	"SMK Muhammadiyah 13 Jakarta",
	"SMK Muhammadiyah 15 Jakarta",
	"SMK Muhammadiyah 2 Jakarta",
	"SMK Muhammadiyah 3 Jakarta",
	"SMK Muhammadiyah 4 Jakarta",
	"SMK Muhammadiyah 5 Jakarta",
	"SMK Muhammadiyah 6 Jakarta",
	"SMK Muhammadiyah 7 Jakarta",
	"SMK Muhammadiyah 9 Jakarta",
	"SMK Multimedia Mandiri",
	"SMK Multimedia Nusantara",
	"SMK Musik Perguruan Cikini",
	"SMK Mutiara 1 Jakarta",
	"SMK Mutiara Bangsa",
	"SMK Mutiara Bangsa 3",
	"SMK Nasional Alfan",
	"SMK Negeri 1",
	"SMK Negeri 10",
	"SMK Negeri 11",
	"SMK Negeri 12",
	"SMK Negeri 13",
	"SMK Negeri 14",
	"SMK Negeri 15",
	"SMK Negeri 16",
	"SMK Negeri 17",
	"SMK Negeri 18",
	"SMK Negeri 19",
	"SMK Negeri 2",
	"SMK Negeri 20",
	"SMK Negeri 21",
	"SMK Negeri 22",
	"SMK Negeri 23",
	"SMK Negeri 24",
	"SMK Negeri 25",
	"SMK Negeri 26",
	"SMK Negeri 27",
	"SMK Negeri 28",
	"SMK Negeri 29",
	"SMK Negeri 3",
	"SMK Negeri 30",
	"SMK Negeri 31",
	"SMK Negeri 32",
	"SMK Negeri 33",
	"SMK Negeri 34",
	"SMK Negeri 35",
	"SMK Negeri 36",
	"SMK Negeri 37",
	"SMK Negeri 38",
	"SMK Negeri 39",
	"SMK Negeri 4",
	"SMK Negeri 40",
	"SMK Negeri 41",
	"SMK Negeri 42",
	"SMK Negeri 43",
	"SMK Negeri 44",
	"SMK Negeri 45",
	"SMK Negeri 46",
	"SMK Negeri 47",
	"SMK Negeri 48",
	"SMK Negeri 49",
	"SMK Negeri 5",
	"SMK Negeri 50",
	"SMK Negeri 51",
	"SMK Negeri 52",
	"SMK Negeri 53",
	"SMK Negeri 54",
	"SMK Negeri 55",
	"SMK Negeri 56",
	"SMK Negeri 57",
	"SMK Negeri 58",
	"SMK Negeri 59",
	"SMK Negeri 6",
	"SMK Negeri 60",
	"SMK Negeri 61",
	"SMK Negeri 62",
	"SMK Negeri 63",
	"SMK Negeri 64",
	"SMK Negeri 65",
	"SMK Negeri 66",
	"SMK Negeri 67",
	"SMK Negeri 68",
	"SMK Negeri 69",
	"SMK Negeri 7",
	"SMK Negeri 70",
	"SMK Negeri 71",
	"SMK Negeri 72",
	"SMK Negeri 73",
	"SMK Negeri 74",
	"SMK Negeri 8",
	"SMK Negeri 9",
	"SMK Nurul Huda",
	"SMK Nurul Iman Jakarta",
	"SMK Nurul Islam Jakarta",
	"SMK Nusantara",
	"SMK Nusantara 1 Jakarta",
	"SMK Nusantara 2 Jakarta",
	"SMK Nusantara Wisata Respati",
	"SMK Otomindo",
	"SMK PGRI 1 Jakarta",
	"SMK PGRI 11 Jakarta",
	"SMK PGRI 15 Jakarta",
	"SMK PGRI 16 Jakarta",
	"SMK PGRI 2 Jakarta",
	"SMK PGRI 20 Jakarta",
	"SMK PGRI 23 Jakarta",
	"SMK PGRI 24 Jakarta",
	"SMK PGRI 28 Jakarta",
	"SMK PGRI 29 Jakarta",
	"SMK PGRI 3 Jakarta",
	"SMK PGRI 31 Jakarta",
	"SMK PGRI 35 Jakarta",
	"SMK PGRI 36 Jakarta",
	"SMK PGRI 37 Jakarta",
	"SMK PGRI 38 Jakarta",
	"SMK PGRI 39 Jakarta",
	"SMK PGRI 4 Jakarta",
	"SMK PGRI 5 Jakarta",
	"SMK PGRI 8 Jakarta",
	"SMK PKP 1 Jakarta",
	"SMK PSKD 1 Jakarta",
	"SMK PSKD 3 Jakarta",
	"SMK Padindi",
	"SMK Pancasila Jakarta",
	"SMK Pandawa",
	"SMK Pandawa Budi Luhur Jakarta",
	"SMK Pangeran Wijayakusuma",
	"SMK Pangudi Rahayu I Jakarta",
	"SMK Pangudi Rahayu II Jakarta",
	"SMK Paramitha 2 Jakarta",
	"SMK Paramitha Jakarta",
	"SMK Pariwisata Sumbangsih",
	"SMK Pasar Minggu Jakarta",
	"SMK Paskita Global",
	"SMK Patmos",
	"SMK Patria Wisata Jakarta",
	"SMK Patriot Nusantara",
	"SMK Pelayaran Bimasakti Jakarta",
	"SMK Pelayaran Dewaruci",
	"SMK Pelayaran Djadajat Jakarta",
	"SMK Pelayaran Jakarta",
	"SMK Pelayaran Jakarta Raya",
	"SMK Pelayaran Jalasena",
	"SMK Pelayaran Malahayati Jakarta",
	"SMK Pelayaran Pembangunan Jakarta",
	"SMK Pelita IV",
	"SMK Pelita Tiga No 1 Jakarta",
	"SMK Pembangun Generasi Emas",
	"SMK Pembangunan",
	"SMK Pembangunan Jaya Yakapi",
	"SMK Perbankan Nasional Jakarta",
	"SMK Perdana Kusuma",
	"SMK Perguruan Cikini Jakarta",
	"SMK Perguruan Rakyat",
	"SMK Perguruan Rakyat 2",
	"SMK Perintis Nasional Jakarta",
	"SMK Permata Bunda I Jakarta",
	"SMK Permata Dunia",
	"SMK Permata Indah",
	"SMK Pertiwi Jakarta",
	"SMK Perwira Jakarta",
	"SMK Petri Jaya",
	"SMK Pluit Raya",
	"SMK Plus Al Musyarrofah",
	"SMK Poncol",
	"SMK Pondok Indah",
	"SMK Prestasi Agung",
	"SMK Prestasi Prima",
	"SMK Prima Wisata",
	"SMK Purnama 1 Jakarta",
	"SMK Purnama 2 Jakarta",
	"SMK Purnama 3 Jakarta",
	"SMK Pusaka 1 Jakarta",
	"SMK Puspita Persada",
	"SMK Putra Mandiri",
	"SMK Putra Nusantara",
	"SMK Putra Satria",
	"SMK RPI Jakarta",
	"SMK Rahayu Mulyo",
	"SMK Raudhatul Jannatunnaim",
	"SMK Reformasi",
	"SMK Remaja Pluit",
	"SMK Respati 1",
	"SMK Respati 2 Jakarta",
	"SMK Rex Mundi",
	"SMK Ristek Jaya Jakarta",
	"SMK Ristek Kikin Jakarta",
	"SMK SPES Patriae",
	"SMK Sahid Jakarta",
	"SMK Said Naum",
	"SMK Santa Lucia",
	"SMK Santa Maria",
	"SMK Santa Theresia",
	"SMK Santo Leo",
	"SMK Santo Paulus",
	"SMK Sari Putra",
	"SMK Satria Jakarta",
	"SMK Satya Bhakti 1 Jakarta",
	"SMK Satya Bhakti 2 Jakarta",
	"SMK Sejahtera Jakarta",
	"SMK Selagan Jaya",
	"SMK Sentosa",
	"SMK Setia Gama",
	"SMK Siliwangi Jakarta",
	"SMK Sismadi",
	"SMK Sriwijaya Jakarta",
	"SMK St Bonaventura Jakarta",
	"SMK Strada 1 Jakarta",
	"SMK Strada 3 Jakarta",
	"SMK Strada II Jakarta",
	"SMK Strada Jakarta",
	"SMK Sumbangsih",
	"SMK Sumpah Pemuda",
	"SMK Swadaya Global School",
	"SMK Syahid",
	"SMK T Kapin Jakarta",
	"SMK Taman Sakti Jakarta",
	"SMK Taman Siswa 1 Jakarta",
	"SMK Taman Siswa 2 Jakarta",
	"SMK Taman Siswa 3 Jakarta",
	"SMK Tanjung Barat",
	"SMK Tanjung Jakarta",
	"SMK Tanjung Priok 1 Jakarta",
	"SMK Tanjung Priok 2 Jakarta",
	"SMK Tarakanita Jakarta",
	"SMK Teknik 10 Nopember",
	"SMK Teladan",
	"SMK Teladan Jakarta",
	"SMK Teladan Utama",
	"SMK Telkom Sandhy Putra Jakarta",
	"SMK Teratai Putih Jakarta",
	"SMK Tirta Sari Surya",
	"SMK Tomang Raya",
	"SMK Trampil Jakarta",
	"SMK Tri Arga 2",
	"SMK Tri Mulia Jakarta",
	"SMK Tri Ratna Jakarta",
	"SMK Tri Sastra 1 Jakarta",
	"SMK Tri Sastra 2 Jakarta",
	"SMK Tridharma Budhidaya",
	"SMK Triguna 1956",
	"SMK Trikarya",
	"SMK Tunas Grafika Informatika",
	"SMK Tunas Harapan",
	"SMK Tunas Markatin",
	"SMK Tunas Pembangunan",
	"SMK Uswatun Hasanah",
	"SMK Walang Jaya",
	"SMK Walisongo Jakarta",
	"SMK Wawasan Nusantara Jakarta",
	"SMK Widya Manggala Jakarta",
	"SMK Widya Patria 2",
	"SMK Wisata Indonesia",
	"SMK Wiyata Satya",
	"SMK Wiyatamandala Bakti Jakarta",
	"SMK Wiyatamandala Jakarta",
	"SMK YMIK Jakarta",
	"SMK YP Darul Mukminin",
	"SMK YP IPPI Jakarta",
	"SMK YP IPPI Petojo",
	"SMK YP Mulia",
	"SMK YPIA Al Falah Jakarta",
	"SMK YPK Kesatuan Jakarta",
	"SMK YPUI Jakarta",
	"SMK Yadika 1 Jakarta",
	"SMK Yadika 2 Jakarta",
	"SMK Yadika 3 Jakarta",
	"SMK Yamas Jakarta",
	"SMK Yandika",
	"SMK Yanindo Jakarta",
	"SMK Yanusa Jakarta",
	"SMK Yapenap Jakarta",
	"SMK Yapermas Jakarta",
	"SMK Yapimda",
	"SMK Yappenda Jakarta",
	"SMK Yapri Jakarta",
	"SMK Yasda",
	"SMK Yaspen",
	"SMK Yaspi Jaya",
	"SMK Yaspia",
	"SMK Yaspia 17",
	"SMK Yusha Jakarta",
	"SMP Negeri 1",
	"SMP Negeri 10",
	"SMP Negeri 100",
	"SMP Negeri 101",
	"SMP Negeri 102",
	"SMP Negeri 103",
	"SMP Negeri 104",
	"SMP Negeri 105",
	"SMP Negeri 106",
	"SMP Negeri 107",
	"SMP Negeri 108",
	"SMP Negeri 109",
	"SMP Negeri 11",
	"SMP Negeri 110",
	"SMP Negeri 111",
	"SMP Negeri 112",
	"SMP Negeri 113",
	"SMP Negeri 114",
	"SMP Negeri 115",
	"SMP Negeri 116",
	"SMP Negeri 117",
	"SMP Negeri 118",
	"SMP Negeri 119",
	"SMP Negeri 12",
	"SMP Negeri 120",
	"SMP Negeri 121",
	"SMP Negeri 122",
	"SMP Negeri 123",
	"SMP Negeri 124",
	"SMP Negeri 125",
	"SMP Negeri 126",
	"SMP Negeri 127",
	"SMP Negeri 128",
	"SMP Negeri 129",
	"SMP Negeri 13",
	"SMP Negeri 130",
	"SMP Negeri 131",
	"SMP Negeri 132",
	"SMP Negeri 133",
	"SMP Negeri 134",
	"SMP Negeri 135",
	"SMP Negeri 136",
	"SMP Negeri 137",
	"SMP Negeri 138",
	"SMP Negeri 139",
	"SMP Negeri 14",
	"SMP Negeri 140",
	"SMP Negeri 141",
	"SMP Negeri 142",
	"SMP Negeri 143",
	"SMP Negeri 144",
	"SMP Negeri 145",
	"SMP Negeri 146",
	"SMP Negeri 147",
	"SMP Negeri 148",
	"SMP Negeri 149",
	"SMP Negeri 15",
	"SMP Negeri 150",
	"SMP Negeri 151",
	"SMP Negeri 152",
	"SMP Negeri 153",
	"SMP Negeri 154",
	"SMP Negeri 155",
	"SMP Negeri 156",
	"SMP Negeri 157",
	"SMP Negeri 158",
	"SMP Negeri 159",
	"SMP Negeri 16",
	"SMP Negeri 160",
	"SMP Negeri 161",
	"SMP Negeri 162",
	"SMP Negeri 163",
	"SMP Negeri 164",
	"SMP Negeri 165",
	"SMP Negeri 166",
	"SMP Negeri 167",
	"SMP Negeri 168",
	"SMP Negeri 169",
	"SMP Negeri 17",
	"SMP Negeri 170",
	"SMP Negeri 171",
	"SMP Negeri 172",
	"SMP Negeri 173",
	"SMP Negeri 174",
	"SMP Negeri 175",
	"SMP Negeri 176",
	"SMP Negeri 177",
	"SMP Negeri 178",
	"SMP Negeri 179",
	"SMP Negeri 18",
	"SMP Negeri 180",
	"SMP Negeri 181",
	"SMP Negeri 182",
	"SMP Negeri 183",
	"SMP Negeri 184",
	"SMP Negeri 185",
	"SMP Negeri 186",
	"SMP Negeri 187",
	"SMP Negeri 188",
	"SMP Negeri 189",
	"SMP Negeri 19",
	"SMP Negeri 190",
	"SMP Negeri 191",
	"SMP Negeri 192",
	"SMP Negeri 193",
	"SMP Negeri 194",
	"SMP Negeri 195",
	"SMP Negeri 196",
	"SMP Negeri 197",
	"SMP Negeri 198",
	"SMP Negeri 199",
	"SMP Negeri 2",
	"SMP Negeri 20",
	"SMP Negeri 200",
	"SMP Negeri 201",
	"SMP Negeri 202",
	"SMP Negeri 203",
	"SMP Negeri 204",
	"SMP Negeri 205",
	"SMP Negeri 206",
	"SMP Negeri 207",
	"SMP Negeri 208",
	"SMP Negeri 209",
	"SMP Negeri 21",
	"SMP Negeri 210",
	"SMP Negeri 211",
	"SMP Negeri 212",
	"SMP Negeri 213",
	"SMP Negeri 214",
	"SMP Negeri 215",
	"SMP Negeri 216",
	"SMP Negeri 217",
	"SMP Negeri 218",
	"SMP Negeri 219",
	"SMP Negeri 22",
	"SMP Negeri 220",
	"SMP Negeri 221",
	"SMP Negeri 222",
	"SMP Negeri 223",
	"SMP Negeri 224",
	"SMP Negeri 225",
	"SMP Negeri 226",
	"SMP Negeri 227",
	"SMP Negeri 228",
	"SMP Negeri 229",
	"SMP Negeri 23",
	"SMP Negeri 230",
	"SMP Negeri 231",
	"SMP Negeri 232",
	"SMP Negeri 233",
	"SMP Negeri 234",
	"SMP Negeri 235",
	"SMP Negeri 236",
	"SMP Negeri 237",
	"SMP Negeri 238",
	"SMP Negeri 24",
	"SMP Negeri 25",
	"SMP Negeri 26",
	"SMP Negeri 27",
	"SMP Negeri 28",
	"SMP Negeri 29",
	"SMP Negeri 3",
	"SMP Negeri 30",
	"SMP Negeri 31",
	"SMP Negeri 32",
	"SMP Negeri 33",
	"SMP Negeri 34",
	"SMP Negeri 35",
	"SMP Negeri 36",
	"SMP Negeri 37",
	"SMP Negeri 38",
	"SMP Negeri 39",
	"SMP Negeri 4",
	"SMP Negeri 40",
	"SMP Negeri 41",
	"SMP Negeri 42",
	"SMP Negeri 43",
	"SMP Negeri 44",
	"SMP Negeri 45",
	"SMP Negeri 46",
	"SMP Negeri 47",
	"SMP Negeri 48",
	"SMP Negeri 49",
	"SMP Negeri 5",
	"SMP Negeri 50",
	"SMP Negeri 51",
	"SMP Negeri 52",
	"SMP Negeri 53",
	"SMP Negeri 54",
	"SMP Negeri 55",
	"SMP Negeri 56",
	"SMP Negeri 57",
	"SMP Negeri 58",
	"SMP Negeri 59",
	"SMP Negeri 6",
	"SMP Negeri 60",
	"SMP Negeri 61",
	"SMP Negeri 62",
	"SMP Negeri 63",
	"SMP Negeri 64",
	"SMP Negeri 65",
	"SMP Negeri 66",
	"SMP Negeri 67",
	"SMP Negeri 68",
	"SMP Negeri 69",
	"SMP Negeri 7",
	"SMP Negeri 70",
	"SMP Negeri 71",
	"SMP Negeri 72",
	"SMP Negeri 73",
	"SMP Negeri 74",
	"SMP Negeri 75",
	"SMP Negeri 76",
	"SMP Negeri 77",
	"SMP Negeri 78",
	"SMP Negeri 79",
	"SMP Negeri 8",
	"SMP Negeri 80",
	"SMP Negeri 81",
	"SMP Negeri 82",
	"SMP Negeri 83",
	"SMP Negeri 84",
	"SMP Negeri 85",
	"SMP Negeri 86",
	"SMP Negeri 87",
	"SMP Negeri 88",
	"SMP Negeri 89",
	"SMP Negeri 9",
	"SMP Negeri 90",
	"SMP Negeri 91",
	"SMP Negeri 92",
	"SMP Negeri 93",
	"SMP Negeri 94",
	"SMP Negeri 95",
	"SMP Negeri 96",
	"SMP Negeri 97",
	"SMP Negeri 98",
	"SMP Negeri 99",
	"Sekolah Rakyat Menengah Atas Negeri 10 Jakarta Selatan",
	"Sekolah Rakyat Menengah Atas Negeri 9 Jakarta Timur",
	"Sma At Taqwa Jakarta",
	"Sma Mardani Leadership School",
	"Smas YP IPPI Petojo Jakarta",
}

// IsValidSekolah memeriksa apakah string sekolah yang diberikan termasuk
// dalam daftar yang valid. String kosong dianggap valid (belum diisi).
func IsValidSekolah(s string) bool {
	if s == "" {
		return true
	}
	for _, v := range SekolahList {
		if v == s {
			return true
		}
	}
	return false
}

type User struct {
	Id           int       `orm:"auto;pk" json:"id"`
	NamaLengkap  string    `orm:"size(255)" json:"nama_lengkap"`
	TanggalLahir *time.Time `orm:"null;column(tanggal_lahir);type(date)" json:"tanggal_lahir,omitempty"`
	Alamat       string    `orm:"type(text)" json:"alamat"`
	Kota         string    `orm:"size(100);null" json:"kota"`
	Provinsi     string    `orm:"size(100);null" json:"provinsi"`
	Kodepos      string    `orm:"size(10);null" json:"kodepos"`
	JenisKelamin Gender    `orm:"size(20)" json:"jenis_kelamin"`
	Email        string    `orm:"size(255);unique" json:"email"`
	NoHandphone  string    `orm:"size(20)" json:"no_handphone"`
	AsalInstansi string    `orm:"column(asal_instansi);size(255);null" json:"asal_instansi"`
	FotoProfil   string    `orm:"size(255);null" json:"foto_profil"`
	Password     string    `orm:"size(255)" json:"-"`
	Role         Role      `orm:"size(20)" json:"role"`

	NPSN              string `orm:"column(npsn);size(50);null" json:"npsn"`
	JenjangSekolah    string `orm:"column(jenjang_sekolah);size(50);null" json:"jenjang_sekolah"`

	// === Onboarding & data tambahan untuk header alat tes ===
	NISN              string `orm:"column(nisn);size(20)" json:"nisn"`
	NIP               string `orm:"column(nip);size(30)" json:"nip"`
	Kelas             string `orm:"column(kelas);size(50)" json:"kelas"`
	Jurusan           string `orm:"column(jurusan);size(100)" json:"jurusan"`
	TempatLahir       string `orm:"column(tempat_lahir);size(100)" json:"tempat_lahir"`
	Kecamatan         string `orm:"column(kecamatan);size(100)" json:"kecamatan"`
	Sekolah           string `orm:"column(sekolah);size(64)" json:"sekolah"`
	ProfileCompleted  bool   `orm:"column(profile_completed);default(false)" json:"profile_completed"`

	// === Detailed Student Identity Fields ===
	NoNIK             string `orm:"column(no_nik);size(30)" json:"no_nik"`
	NoKK              string `orm:"column(no_kk);size(30)" json:"no_kk"`
	NomorAktaLahir    string `orm:"column(nomor_akta_lahir);size(50)" json:"nomor_akta_lahir"`
	Agama             string `orm:"column(agama);size(30)" json:"agama"`
	TempatTinggal     string `orm:"column(tempat_tinggal);size(255)" json:"tempat_tinggal"`
	ModeTransportasi  string `orm:"column(mode_transportasi);size(255)" json:"mode_transportasi"`
	AnakKe            int    `orm:"column(anak_ke)" json:"anak_ke"`
	JumlahBersaudara  int    `orm:"column(jumlah_bersaudara)" json:"jumlah_bersaudara"`
	RiwayatPenyakit   string `orm:"column(riwayat_penyakit);type(text)" json:"riwayat_penyakit"`

	CreatedAt time.Time `orm:"auto_now_add;type(datetime)" json:"created_at"`
	UpdatedAt time.Time `orm:"auto_now;type(datetime)" json:"updated_at"`
}

func (u *User) TableName() string {
	return "users"
}

// HashPassword hashes the user's password
func (u *User) HashPassword() error {
	hashedPassword, err := bcrypt.GenerateFromPassword([]byte(u.Password), bcrypt.DefaultCost)
	if err != nil {
		return err
	}
	u.Password = string(hashedPassword)
	return nil
}

// CheckPassword verifies the password
func (u *User) CheckPassword(password string) bool {
	err := bcrypt.CompareHashAndPassword([]byte(u.Password), []byte(password))
	return err == nil
}

func init() {
	orm.RegisterModel(new(User))
}
